version: 1.0.{build}
image: Visual Studio 2019
configuration: Release
shallow_clone: true
before_build:
- cmd: dotnet restore
build:
  project: HueLightDJ.sln
  publish_aspnet_core: true
  verbosity: minimal
after_build:
- cmd: dotnet publish HueLightDJ.Web -o ..\AppOutput\HueLightDJ.Web -c Release
test: off
artifacts:
- path: AppOutput\HueLightDJ.Web
  name: HueLightDJ.Web
  type: WebDeployPackage